### ISSUE TITLE
Set non-plugin specific parameters

### ISSUE THREAD

**Issue by kristiyip** [jspsych/jsPsych-Redux-GUI#17]
Ex: data, on_finish, timing_post_trial

**Comment by jodeleeuw** [comment]
@GavinQ1 This still needs to be implemented. All plugins support these three parameters, so they should appear no matter what.

`on_finish` is a function

`timing_post_trial` has been renamed to `post_trial_gap` and is an integer. 

`data` is an object. It's what allows you to tag trials with custom values. An example might be:

```js
var trial = {
  type: 'image-keyboard-response',
  stimulus: 'image1.png',
  data: { image_type: 'congruent', block: 1 }
}
```

For now, I think a simple text area component where people enter key: value pairs separated by new lines could work. 

```
image_type: congruent
block: 1
```

Or if you think something more complex makes sense, that's fine with me.
